export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const INIT_PURCHASE_ORDER = 'INIT_PURCHASE_ORDER';
export const PURCHASE_ORDER_SUCCESS = 'PURCHASE_ORDER_SUCCESS';
export const PURCHASE_ORDER_FAILURE = 'PURCHASE_ORDER_FAILURE';
export const PURCHASE_BURGER = 'PURCHASE_BURGER';

export const SET_ERROR = 'SET_ERROR';