export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const INIT_PURCHASE_ORDER = 'INIT_PURCHASE_ORDER';
export const PURCHASE_ORDER_SUCCESS = 'PURCHASE_ORDER_SUCCESS';
export const PURCHASE_ORDER_FAILURE = 'PURCHASE_ORDER_FAILURE';
export const PURCHASE_BURGER = 'PURCHASE_BURGER';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';


export const INIT_AUTHENTICATE = 'INIT_AUTHENTICATE';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';
export const LOG_OUT = 'LOG_OUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_ERROR = 'SET_ERROR';